codecrafters-io/build-your-own-redis

compiled_starters/redis-starter-javascript/app/main.js
solutions/javascript/concurrent-clients/code/app/main.js
solutions/javascript/init/code/app/main.js
solutions/javascript/init/diff/app/main.js.diff
solutions/javascript/init/explanation.md
solutions/javascript/ping-pong-multiple/code/app/main.js
solutions/javascript/ping-pong/code/app/main.js
solutions/javascript/ping-pong/diff/app/main.js.diff
starter_templates/javascript/app/main.js

Incorporates feedback from https://github.com/codecrafters-io/build-your-own-redis/pull/21 + propagates to other stages

remove socket.pipe from js stage 1

---

solutions/javascript/init/code/README.md
solutions/javascript/init/code/app/main.js
solutions/javascript/init/code/codecrafters.yml
solutions/javascript/init/code/spawn_redis_server.sh
solutions/javascript/init/diff/app/main.js.diff
solutions/javascript/init/explanation.md

The solution for this stage was created before we setup the reviews feature. You'll notice that this PR doesn't
target the `main` branch, this is because the `main` branch already contains the "unreviewed" solution. 
This PR doesn't have to be merged, it's created for the sole purpose of being reviewed using GitHub's Pull 
Request UI. Any changes recommended here will be later merged into the `main` branch.

Add solution for javascript - #1 (Bind to a port)

---

solutions/ruby/init/code/README.md
solutions/ruby/init/code/app/server.rb
solutions/ruby/init/code/codecrafters.yml
solutions/ruby/init/code/spawn_redis_server.sh
solutions/ruby/init/diff/app/server.rb.diff
solutions/ruby/init/explanation.md

The solution for this stage was created before we setup the reviews feature. You'll notice that this PR doesn't
target the `main` branch, this is because the `main` branch already contains the "unreviewed" solution. 
This PR doesn't have to be merged, it's created for the sole purpose of being reviewed using GitHub's Pull 
Request UI. Any changes recommended here will be later merged into the `main` branch.

Add solution for ruby - #1 (Bind to a port)

---

solutions/go/init/code/README.md
solutions/go/init/code/app/server.go
solutions/go/init/code/codecrafters.yml
solutions/go/init/code/spawn_redis_server.sh
solutions/go/init/diff/app/server.go.diff
solutions/go/init/explanation.md

The solution for this stage was created before we setup the reviews feature. You'll notice that this PR doesn't
target the `main` branch, this is because the `main` branch already contains the "unreviewed" solution. 
This PR doesn't have to be merged, it's created for the sole purpose of being reviewed using GitHub's Pull 
Request UI. Any changes recommended here will be later merged into the `main` branch.

Add solution for go - #1 (Bind to a port)

---

solutions/go/ping-pong/code/README.md
solutions/go/ping-pong/code/app/server.go
solutions/go/ping-pong/code/codecrafters.yml
solutions/go/ping-pong/code/spawn_redis_server.sh
solutions/go/ping-pong/diff/app/server.go.diff
solutions/go/ping-pong/explanation.md

The solution for this stage was created before we setup the reviews feature. You'll notice that this PR doesn't
target the `main` branch, this is because the `main` branch already contains the "unreviewed" solution. 
This PR doesn't have to be merged, it's created for the sole purpose of being reviewed using GitHub's Pull 
Request UI. Any changes recommended here will be later merged into the `main` branch.

Add solution for go - #2 (Respond to PING)

---

compiled_starters/redis-starter-rust/Cargo.toml
solutions/rust/init/code/Cargo.toml
solutions/rust/ping-pong/code/Cargo.toml
starter_templates/rust/Cargo.toml

update Rust edition

---

.github/workflows/test.yml
compiled_starters/redis-starter-rust/spawn_redis_server.sh
dockerfiles/rust-1.62.Dockerfile
solutions/rust/01-init/code/spawn_redis_server.sh
solutions/rust/02-ping-pong/code/spawn_redis_server.sh
solutions/rust/03-ping-pong-multiple/code/spawn_redis_server.sh
solutions/rust/04-concurrent-clients/code/spawn_redis_server.sh
solutions/rust/05-echo/code/spawn_redis_server.sh
solutions/rust/06-set_get/code/spawn_redis_server.sh
solutions/rust/07-expiry/code/spawn_redis_server.sh
starter_templates/rust/spawn_redis_server.sh

Reverts codecrafters-io/build-your-own-redis#67

Revert "Improve Rust cache handling, avoid /tmp directory"

---

compiled_starters/rust/spawn_redis_server.sh
solutions/rust/01-init/code/spawn_redis_server.sh
starter_templates/rust/spawn_redis_server.sh

Run tests for #95

---

compiled_starters/csharp/README.md
compiled_starters/csharp/codecrafters-redis.csproj
compiled_starters/csharp/codecrafters.yml
dockerfiles/dotnet-8.0.Dockerfile
solutions/csharp/01-init/code/README.md
solutions/csharp/01-init/code/codecrafters-redis.csproj
solutions/csharp/01-init/code/codecrafters.yml
solutions/csharp/01-init/diff/src/Server.cs.diff
starter-repository-definitions.yml
starter_templates/codecrafters.yml
starter_templates/csharp/codecrafters-redis.csproj

Leaving dotnet6 docker file in case old project still has to run against it?

Upgrade csharp project to use dotnet8. 

---

compiled_starters/php/codecrafters.yml
dockerfiles/php-8.3.Dockerfile
solutions/php/01-init/code/codecrafters.yml
starter_templates/codecrafters.yml

I kept the older versions in comment in codecrafters.yml, since the older versions are still available

Add php8.3 support for Codecrafters Redis challenge

---

compiled_starters/javascript/.gitignore
compiled_starters/javascript/README.md
compiled_starters/javascript/codecrafters.yml
compiled_starters/javascript/package-lock.json
compiled_starters/javascript/package.json
dockerfiles/nodejs-21.Dockerfile
solutions/javascript/01-init/code/.gitignore
solutions/javascript/01-init/code/README.md
solutions/javascript/01-init/code/codecrafters.yml
solutions/javascript/01-init/code/package-lock.json
solutions/javascript/01-init/code/package.json
starter-repository-definitions.yml
starter_templates/codecrafters.yml
starter_templates/javascript/.gitignore
starter_templates/javascript/package-lock.json
starter_templates/javascript/package.json

CC-1157: add dependency resolution for js projects.

---

course-definition.yml

* Use unordered list for Notes section
* Remove some unnecessary spaces

Make small fixes to persistence 1 instructions

---

.gitignore
course-definition.yml

This pull request adds stage descriptions for the transactions extension. It includes changes to the `course_definition_tester` file.

Add stage descriptions for transactions extension

---

course-definition.yml

Thanks to @visiongirles for highlighting this!

Update stream_key and other_stream_key lengths in course-definition.yml

---

course-definition.yml

The commit message summarizes the changes made in the commit. In this case, the commit message could be:
"Add support for INCR command and update course definition"
This message is concise and under 80 characters, which is a good practice for commit messages.

Add support for INCR command and update course definition

---

compiled_starters/elixir/.formatter.exs
solutions/elixir/01-jm1/code/.formatter.exs

The commit message could be: "Add formatter configuration for Elixir and Haskell"

Fix conflicting file mappings

---

dockerfiles/crystal-1.1.Dockerfile
dockerfiles/dotnet-6.0.Dockerfile
dockerfiles/dotnet-8.0.Dockerfile
dockerfiles/gleam-1.0.Dockerfile
dockerfiles/gleam-1.4.Dockerfile
dockerfiles/kotlin-2.0.Dockerfile
dockerfiles/ocaml-5.2.0.Dockerfile
dockerfiles/php-7.4.Dockerfile
dockerfiles/php-8.3.Dockerfile
dockerfiles/ruby-3.3.Dockerfile
dockerfiles/rust-1.43.Dockerfile
dockerfiles/rust-1.54.Dockerfile
dockerfiles/rust-1.62.Dockerfile
dockerfiles/rust-1.68.Dockerfile
dockerfiles/rust-1.70.Dockerfile
dockerfiles/rust-1.76.Dockerfile
dockerfiles/rust-1.77.Dockerfile
dockerfiles/zig-0.12.Dockerfile

remove COPY app instruction

---

dockerfiles/clojure-1.10.3.Dockerfile
dockerfiles/clojure-1.11.3.Dockerfile
dockerfiles/cpp-23.Dockerfile
dockerfiles/dotnet-6.0.Dockerfile
dockerfiles/dotnet-8.0.Dockerfile
dockerfiles/gleam-1.0.Dockerfile
dockerfiles/haskell-9.4.Dockerfile
dockerfiles/java-21.Dockerfile
dockerfiles/rust-1.54.Dockerfile
dockerfiles/rust-1.62.Dockerfile
dockerfiles/rust-1.68.Dockerfile
dockerfiles/rust-1.70.Dockerfile
dockerfiles/rust-1.76.Dockerfile
dockerfiles/rust-1.77.Dockerfile
dockerfiles/scala-2.12.Dockerfile
dockerfiles/zig-0.12.Dockerfile

replace-submission-dir

---

compiled_starters/gleam/src/main.gleam
compiled_starters/go/app/server.go
compiled_starters/python/app/main.py
compiled_starters/rust/src/main.rs
compiled_starters/zig/src/main.zig
solutions/gleam/01-jm1/code/src/main.gleam
solutions/gleam/01-jm1/diff/src/main.gleam.diff
solutions/gleam/01-jm1/explanation.md
solutions/go/01-jm1/code/app/server.go
solutions/go/01-jm1/diff/app/server.go.diff
solutions/go/01-jm1/explanation.md
solutions/python/01-jm1/code/app/main.py
solutions/python/01-jm1/diff/app/main.py.diff
solutions/python/01-jm1/explanation.md
solutions/rust/01-jm1/code/src/main.rs
solutions/rust/01-jm1/diff/src/main.rs.diff
solutions/rust/01-jm1/explanation.md
solutions/zig/01-jm1/diff/src/main.zig.diff
solutions/zig/01-jm1/explanation.md
starter_templates/gleam/code/src/main.gleam
starter_templates/go/code/app/server.go
starter_templates/python/code/app/main.py
starter_templates/rust/code/src/main.rs
starter_templates/zig/code/src/main.zig

- update uncomment usage
- update uncomment usage

fix double uncomment

---

compiled_starters/php/app/main.php
solutions/php/01-jm1/code/app/main.php
solutions/php/01-jm1/diff/app/main.php.diff
starter_templates/php/code/app/main.php

PSR-12: Extended Coding Style
> The closing ?> tag MUST be omitted from files containing only PHP.
https://www.php-fig.org/psr/psr-12/

[php] Delete closing ?>

---

course-definition.yml

Thanks, @jamestjw, for highlighting the issue!

Fix typo in XREAD command #hw1

---

compiled_starters/go/go.mod
compiled_starters/haskell/package.yaml
compiled_starters/haskell/stack.yaml
compiled_starters/rust/Cargo.toml
solutions/go/01-jm1/code/go.mod
solutions/go/02-rg2/code/go.mod
solutions/haskell/01-jm1/code/package.yaml
solutions/haskell/01-jm1/code/stack.yaml
solutions/rust/01-jm1/code/Cargo.toml
solutions/rust/02-rg2/code/Cargo.toml
starter_templates/go/code/go.mod
starter_templates/haskell/code/package.yaml
starter_templates/haskell/code/stack.yaml
starter_templates/rust/code/Cargo.toml

remove DON'T EDIT banners + empty lines and stuff

remove DON'T EDIT banners + empty lines and stuff

---

compiled_starters/java/.codecrafters/compile.sh
compiled_starters/java/codecrafters.yml
compiled_starters/java/your_program.sh
dockerfiles/java-24.Dockerfile
solutions/java/01-jm1/code/.codecrafters/compile.sh
solutions/java/01-jm1/code/codecrafters.yml
solutions/java/01-jm1/code/your_program.sh
solutions/java/02-rg2/code/.codecrafters/compile.sh
solutions/java/02-rg2/code/codecrafters.yml
solutions/java/02-rg2/code/your_program.sh
starter_templates/java/code/.codecrafters/compile.sh

Upgrade Java to 24

---

course-definition.yml

Context:
I added an explanation in Hints as well:

Add notes re: `listening-port` #eh4 #zn8

---

course-definition.yml

Tweak instructions #jz6

---

course-definition.yml

Fix md issue in Lists description

---

course-definition.yml
stage_descriptions/persistence-rdb-01-zg5.md
stage_descriptions/replication-01-bw1.md

…the latest Redis documentation for replication and persistence.

Update more broken links

---

stage_descriptions/base-05-qq0.md

Context:
https://secure.helpscout.net/conversation/3063942071/9557#thread-9329214623

Tweak #qq0 ECHO command

---

stage_descriptions/lists-10-ec3.md

Clarified the usage and behavior of the BLPOP command, including blocking behavior, response format, and client interaction.

Revise "Blocking retrieval" (stage 17 - #ec3)
